print("Whats your name?")
nameUser= input()
print("How old are you?")
yearsUser = input()
print("Where are you from?")
cityUser = input()
print("This is " + nameUser)
print("He(she) is " + yearsUser)
print("He(she) live in " + cityUser)